# Generated by Django 2.2.4 on 2019-11-03 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipments',
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_destination', to='core.City')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_origin', to='core.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment', to='core.Journey'),
        ),
        migrations.AddField(
            model_name='user',
            name='journeys',
            field=models.ManyToManyField(to='core.Journey'),
        ),
    ]
