# Generated by Django 2.2.4 on 2020-01-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191226_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='_avatar',
        ),
        migrations.AlterField(
            model_name='user',
            name='_avatar',
            field=models.CharField(blank=True, db_column='avatar', max_length=1024, null=True),
        ),
    ]
