# Generated by Django 2.2.4 on 2019-11-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191127_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journey',
            old_name='phone',
            new_name='_phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='_phone',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='email',
        ),
        migrations.AddField(
            model_name='journey',
            name='_email',
            field=models.CharField(blank=True, db_column='cemail', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='_email',
            field=models.CharField(blank=True, db_column='cemail', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='_phone',
            field=models.CharField(blank=True, db_column='phone', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='_phone',
            field=models.CharField(blank=True, db_column='phone', max_length=30, null=True),
        ),
    ]
