# Generated by Django 2.2.4 on 2019-11-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191103_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
