# Generated by Django 2.2.4 on 2019-11-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191127_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='_destination',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='_origin',
        ),
        migrations.AddField(
            model_name='journey',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_destination', to='core.City'),
        ),
        migrations.AddField(
            model_name='journey',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_origin', to='core.City'),
        ),
    ]
