# Generated by Django 2.2.4 on 2019-12-03 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191127_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='destination',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='journey_destination', to='core.City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journey',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='journey_origin', to='core.City'),
            preserve_default=False,
        ),
    ]
