# Generated by Django 2.2.4 on 2019-12-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191220_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
