# Generated by Django 2.2.4 on 2019-12-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191220_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='successful',
            field=models.BooleanField(default=True),
        ),
    ]
