# Generated by Django 2.2.4 on 2019-12-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_journey_successful'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='available_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='journey',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
