# Generated by Django 2.2.4 on 2019-12-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='successful',
        ),
    ]
