# Generated by Django 2.2.4 on 2019-12-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_journey_successful'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='successful',
            field=models.BooleanField(default=True),
        ),
    ]
